language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t rvt/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rvt/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "seekster-test"
  env: "Seekstertest-env"
  bucket_name: "elasticbeanstalk-us-east-1-882975227256"
  bucket_path: "seekster-test"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
